apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "azure-api-management-gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "azure-api-management-gateway.name" . }}
    helm.sh/chart: {{ include "azure-api-management-gateway.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.service.endpoint: {{ .Values.gateway.endpoint | quote }}
  telemetry.metrics.local: {{ .Values.telemetry.metrics.local | quote }}
  telemetry.metrics.local.statsd.endpoint: {{ .Values.telemetry.metrics.localStatsd.endpoint | quote }}
  telemetry.metrics.local.statsd.sampling: {{ .Values.telemetry.metrics.localStatsd.sampling | quote }}
  telemetry.metrics.local.statsd.tag-format: {{ .Values.telemetry.metrics.localStatsd.tagFormat | quote }}
  telemetry.metrics.cloud: {{ .Values.telemetry.metrics.cloud | quote }}
  telemetry.logs.std: {{ .Values.telemetry.logs.std | quote }}
  telemetry.logs.local: {{ .Values.telemetry.logs.local | quote }}
  telemetry.logs.local.localsyslog.endpoint: {{ .Values.telemetry.logs.localConfig.localsyslog.endpoint | quote }}
  telemetry.logs.local.localsyslog.facility: {{ .Values.telemetry.logs.localConfig.localsyslog.facility | quote }}
  telemetry.logs.local.rfc5424.endpoint: {{ .Values.telemetry.logs.localConfig.rfc5424.endpoint | quote }}
  telemetry.logs.local.rfc5424.facility: {{ .Values.telemetry.logs.localConfig.rfc5424.facility | quote }}
  telemetry.logs.local.journal.endpoint: {{ .Values.telemetry.logs.localConfig.journal.endpoint | quote }}