apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "azure-api-management-gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "azure-api-management-gateway.name" . }}
    helm.sh/chart: {{ include "azure-api-management-gateway.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "azure-api-management-gateway.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "azure-api-management-gateway.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/proxysecret: {{ include (print $.Template.BasePath "/azure-proxy-secret.yaml") . | sha256sum }}
      {{ if .Values.dapr.enabled -}}
        dapr.io/enabled: "true"
        {{ if .Values.dapr.appId -}}
        dapr.io/app-id: {{ .Values.dapr.appId | quote }}
        {{ end }}
        dapr.io/config: {{ .Values.dapr.config | quote }}
        dapr.io/log-as-json: {{ .Values.dapr.logging.useJsonOutput | quote }}
        dapr.io/log-level: {{ .Values.dapr.logging.level | quote }}
      {{ end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        {{- if  and .Values.monitoring.workspaceId .Values.monitoring.ingestionKey }}
        - name: {{ .Chart.Name }}-monitoring
          image: linuxgeneva-microsoft.azurecr.io/genevamdsd
          ports:
          - name: fluentd
            containerPort: 5001
          env:
          - name: workspace_key
            valueFrom:
              secretKeyRef:
                name: {{ .Chart.Name }}-monitoring-key
                key: monitoring-key
          envFrom:
          - configMapRef:
              name: {{ .Chart.Name }}-monitoring-env
          volumeMounts:
            - mountPath: /geneva/geneva_auth
              name: monitoring-temp
            - mountPath: /geneva/geneva_logs
              name: monitoring-temp
            - mountPath: /geneva/geneva_config
              name: monitoring-config
        {{- end }} 
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "azure-api-management-gateway.fullname" . }}
          {{ if .Values.Azure.proxySettings.isProxyEnabled }}
            - secretRef:
                name: proxy-config
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.gateway.httpPort | int }}
            - name: https
              containerPort: {{ .Values.gateway.httpsPort | int }}
        {{- if  and .Values.Azure.proxySettings.isProxyEnabled .Values.Azure.proxySettings.proxyCert }}
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs/
              readOnly: false
            - mountPath: /usr/local/share/ca-certificates/proxy-cert.crt
              subPath: proxy-cert.crt
              name: proxy-certstore
        {{- end }}
          env:
            - name: config.service.auth
              valueFrom:
                secretKeyRef:
                  name: {{ include "azure-api-management-gateway.fullname" . }}
                  key: gateway-key
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      
    
      volumes:
        {{- if  and .Values.Azure.proxySettings.isProxyEnabled .Values.Azure.proxySettings.proxyCert }}
        - name: proxy-certstore
          secret:
            secretName: proxy-cert
        - name: ssl-certs
          emptyDir: {}
        {{- end }}
        {{- if  .Values.monitoring.workspaceId }}
        - name: monitoring-temp
          emptyDir: {}
        - name: monitoring-config
          configMap:
            name: {{ .Chart.Name }}-monitoring-config
        {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}